---

- name: install the memcached packages
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items: '{{ memcached_ubuntu_pkgs }}'
  environment: '{{ memcached_env }}'

- name: update the memcached configuration file
  template:
    src: memcached_debian.j2
    dest: /etc/memcached.conf
  notify: restart memcached

