---

- include: redhat.yml
  when: ansible_os_family == "Redhat"

- include: debian.yml
  when: ansible_os_family == "Debian"

- name: get the current max open file descriptors
  shell: cat /proc/sys/fs/file-max
  register: file_max

- name: set the max open file descriptors (if larger then current)
  sysctl:
    name: fs.file-max
    value: '{{ memcached_fs_file_max }}'
    state: present
  when: '{{ memcached_fs_file_max > file_max.stdout|int }}'

- name: start and enable the memcached service
  service:
    name: memcached
    state: restarted
    enabled: yes
