---

- include: redhat.yml
  when: ansible_os_family == "Redhat"

- include: debian.yml
  when: ansible_os_family == "Debian"

- name: update the memcached configuration file
  template: src=memcached_redhat.j2 dest=/etc/sysconfig/memcached
  notify:
   - restart memcached
  when: ansible_os_family == "RedHat"

- name: update the memcached configuration file 
  template: src=memcached_debian.j2 dest=/etc/memcached.conf
  notify: restart memcached
  when: ansible_os_family == "Debian"

- name: set the max open file descriptors
  sysctl: name=fs.file-max value={{ memcached_fs_file_max }} state=present

- name: start and enable the memcached service
  service: name=memcached state=started enabled=yes
