---

- name: install the memcached packages
  yum: name={{ item }} state=present
  with_items: '{{ memcached_redhat_pkgs }}'
  when: ansible_os_family == "RedHat"

- name: update the memcached configuration file
  template: src=memcached_redhat.j2 dest=/etc/sysconfig/memcached
  notify:
   - restart memcached
  when: ansible_os_family == "RedHat"
